name: decay

on:
  workflow_dispatch: # manual trigger
  # schedule:
  #   - cron: "0 * * * *" # every hour

jobs:
  decay:
    runs-on: ubuntu-latest
    steps:
      - name: setup repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1

      - name: setup deps
        run: npm install

      - name: radiate
        run: npm run start
        env:
          KEYFILE: ${{ secrets.KEYFILE }}

      - name: commit status file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update status
          file_pattern: status.json distributions.json
